---
title: Natural Thai Network
author: NTN Admin
email: webmaster@naturalthai.network
description: |-
  The Natural Thai Network connects students with expert Thai teachers.

  We promote natural Thai learning approaches, known as "comprehensible input", and our partners are inspired by such figures as Dr Stephen Krashen, Dr James Marvin Brown, Dr Adrian 'Buzz' Palmer, Kristian Peltonen, Pablo Pankun Román, and many others.
baseurl: "/ubuild-jekyll"
url: ''
defaults:
- scope:
    path: ''
  values:
    layout: default
plugins:
- jekyll-feed
- jekyll-menus
